### ISSUE TITLE
Add the generation of auto-completion scripts and putting them where they need to be in order to take effect.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/homebrew-mirrord#2]
https://github.com/metalbear-co/mirrord/pull/1949 adds completion scripts generation.
I think we need to call that new subcommand and generate the scripts after installing mirrord, and also add whatever is needed so those scripts are "installed" (sourcing them in `.bashrc` or something like that).

That way users installing mirrord with homebrew would have autocompletion without needing to take further action.

**Comment by aviramha** [comment]
Sounds good, though I think it should be a prompt asking the user whether they want it.

**Comment by t4lz** [comment]
This might be a helpful example: https://github.com/Homebrew/homebrew-core/blob/b7fc1c0b32c6f283049a0b52ce13780011bc1db8/Formula/h/hub.rb#L41-L43

**Comment by bradschwartz** [comment]
Hey @t4lz I contributed https://github.com/metalbear-co/mirrord/pull/1949 , I'm happy to contribute the change here for this as well.

**Comment by infiniteregrets** [comment]
@bradschwartz that sounds awesome! i'll assign it to you, let us know if you need any help (:

**Comment by bradschwartz** [comment]
Just as an FYI to anyone who sees this in the future - we took a stab at this in #3 but there were issues with homebrew actually running the mirrord binary, most likely due to it being a universal binary. Currently it's just going to print out whenever some installs `mirrord` via brew.

Unassigning myself from this issue for now.
